# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias',
            name='profesor',
        ),
    ]
