# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_remove_materias_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='veces',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
