# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0003_materias_veces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias',
            name='veces',
        ),
    ]
