# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0002_materias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesores',
            name='asignatura',
        ),
    ]
