# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0003_remove_profesores_asignatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias',
            name='profesor',
        ),
        migrations.DeleteModel(
            name='materias',
        ),
    ]
