# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_remove_materias_profesor'),
        ('profesores', '0004_auto_20171117_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesores',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materias.materias'),
        ),
    ]
