# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0005_profesores_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesores',
            name='calle',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
