# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('cuerpo', models.TextField(max_length=100)),
            ],
        ),
    ]
