# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticias',
            old_name='cuerpo',
            new_name='Cuerpo',
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='titulo',
            new_name='Titulo',
        ),
    ]
