# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20171204_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='Logo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
