# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticias_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='Logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
