# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=70)),
                ('sexo', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('fechaMatricula', models.DateField()),
            ],
        ),
    ]
