# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Castigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='alumnos',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profesores.profesores'),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='nota',
            field=models.ManyToManyField(to='alumnos.Castigos'),
        ),
    ]
