# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20171108_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='nota',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='castigos',
            field=models.ManyToManyField(blank=True, to='alumnos.Castigos'),
        ),
    ]
