# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_auto_20171113_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='castigos',
            name='tipo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
